apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: agent-service-ingressroute
  namespace: getourhome
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/api/agents`)
      kind: Rule
      services:
        - name: agent-service
          port: 8080
